# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer/Docs_Diagrams.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_docsAndDiag(object):
    def setupUi(self, docsAndDiag):
        docsAndDiag.setObjectName("docsAndDiag")
        docsAndDiag.resize(697, 608)
        self.docsTab = QtWidgets.QWidget()
        self.docsTab.setObjectName("docsTab")
        self.pushButton = QtWidgets.QPushButton(self.docsTab)
        self.pushButton.setGeometry(QtCore.QRect(10, 270, 161, 28))
        self.pushButton.setObjectName("pushButton")
        docsAndDiag.addTab(self.docsTab, "")
        self.diagramTab = QtWidgets.QWidget()
        self.diagramTab.setObjectName("diagramTab")
        self.diagPrompt = QtWidgets.QTextEdit(self.diagramTab)
        self.diagPrompt.setGeometry(QtCore.QRect(130, 260, 411, 41))
        self.diagPrompt.setObjectName("diagPrompt")
        self.diagGenerate = QtWidgets.QPushButton(self.diagramTab)
        self.diagGenerate.setGeometry(QtCore.QRect(300, 310, 93, 28))
        self.diagGenerate.setObjectName("diagGenerate")
        docsAndDiag.addTab(self.diagramTab, "")

        self.retranslateUi(docsAndDiag)
        docsAndDiag.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(docsAndDiag)

    def retranslateUi(self, docsAndDiag):
        _translate = QtCore.QCoreApplication.translate
        docsAndDiag.setWindowTitle(_translate("docsAndDiag", "TabWidget"))
        self.pushButton.setText(_translate("docsAndDiag", "Add Document"))
        docsAndDiag.setTabText(docsAndDiag.indexOf(self.docsTab), _translate("docsAndDiag", "Docs"))
        self.diagGenerate.setText(_translate("docsAndDiag", "Send"))
        docsAndDiag.setTabText(docsAndDiag.indexOf(self.diagramTab), _translate("docsAndDiag", "Diagrams"))
